### PR TITLE
Node tests

### PR DESCRIPTION
**Pull request by dinagraves**
- multiple nodes test

### CODE REVIEW

**Comment by dinagraves** [comment]
Added a generic test because a lot of the samples only need to build and don't need any cleanup.

**Comment by dinagraves** [comment]
Created triggers for all 3 node samples.

**Comment by dinagraves** [comment]
Note: It looks like it's only those 2 node samples that don't require any cleanup. Not sure about the placement for the no-cleanup-test.cloudbuild.yaml.  

It's so simple, we could change this to an inline config in the trigger?  @glasnt What do you think?

**Comment by glasnt** [comment]
I like the top level test you've made!

I think it'd be useful to name it something other than "no-cleanup-test", as some dirs have cloudbuild.yaml files for reasons other than cleanup. Maybe something like "build-sample.cloudbuild.yaml"?

I'm also not sure about when/if examples should have cloudbuild.yaml files in their own folder for use in snippets, but that's more to do with documentation rather than testing.

**Pull request merged**
