### PR TITLE
Add remote builder pattern.

### PR DESCRIPTION
**Pull request by agmsb**
Open to feedback! I have worked with a handful of folks looking for examples on how to run a potentially more expensive build step separately from the rest of a given build to conserve costs. This pattern displays how to do so. 

(first time contributing here, so please let me know if there are other guidelines for adding examples. thank you!)

### CODE REVIEW

**Comment by dinagraves** [comment]
Thank you!  Can you add license headers?

**Review by dinagraves — CHANGES_REQUESTED** [review]
Please add license headers

**Comment by agmsb** [comment]
Quickly checking in - please let me know if I need to add anything else to make this useful!

**Review by dinagraves — APPROVED** [review]

**Comment by dinagraves** [comment]
Sry about that! Next time feel free to use the re-request review button so it comes back into my Pull Requests tab: 
image

**Pull request merged**
