### PR TITLE
Nityaravi patch 1

### PR DESCRIPTION
**Pull request by nityaravi**
Added region tags to pull in snippets for cl/508160127

### CODE REVIEW

**Comment by psimakov** [comment]
I reviewed and it looks good to me.

**Review by averikitsch — APPROVED** [review]

**Comment by averikitsch** [comment]
Approving, but Nitya will update all region tags to use prefix: `cloudbuild_`

**Comment by averikitsch** [comment]
@psimakov Can you follow these instructions to approve this PR https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews?

**Review by psimakov — APPROVED** [review]
LGTM

**Comment by psimakov** [comment]
One test failed above:
https://console.cloud.google.com/cloud-build/builds/685db1c6-62d9-4080-a82f-defbc9037ac7?project=786554430557

I reviewed the logs and retriggered the test as the error was transient. This has succeeded:
https://console.cloud.google.com/cloud-build/builds/da7240fc-6b46-4fcf-8f99-7cd6257ec979?project=786554430557 

So we are good to merge.

**Pull request merged**
